#include <gtest/gtest.h>
#include "exo2.hpp"

TEST(Exo2, Basic)
{
  std::string text = "youpi    les amis !";
  const std::string expected = "! amis les    youpi";
  reverse_words(text);
  EXPECT_EQ(expected, text);
}

TEST(Exo2, Empty)
{
  std::string text;
  const std::string expected;
  reverse_words(text);
  EXPECT_EQ(expected, text);
}

TEST(Exo2, OnlySpaces)
{
  std::string text = "         ";
  const std::string expected = text;
  reverse_words(text);
  EXPECT_EQ(expected, text);
}

TEST(Exo2, OneWord)
{
  std::string text = "onlyoneword";
  const std::string expected = text;
  reverse_words(text);
  EXPECT_EQ(expected, text);
}

TEST(Exo2, BigText)
{
  std::string text =
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at varius "
      "velit, ac varius massa. Integer iaculis dolor vel nunc pharetra "
      "molestie. Vivamus viverra justo est, a rutrum magna condimentum sed. "
      "Mauris odio leo, luctus vestibulum auctor eu, feugiat sed nisi. "
      "Vestibulum consequat porta ligula, non sagittis nisi vulputate ac. "
      "Morbi gravida tortor sit amet leo fringilla, consequat tincidunt mi "
      "commodo. Pellentesque ac lorem tempor, aliquet nisl at, pharetra dolor. "
      "Nam id semper leo. Sed mattis diam sed faucibus aliquam. Suspendisse "
      "quis augue imperdiet, pellentesque nunc id, faucibus dui. Donec varius "
      "orci finibus quam euismod dignissim. Donec ultrices, purus eu pharetra "
      "feugiat, urna massa viverra libero, ac placerat orci lorem quis tortor. "
      "Nulla facilisi. Interdum et malesuada fames ac ante ipsum primis in "
      "faucibus. Fusce vulputate consectetur libero id semper. Aliquam "
      "pellentesque lorem maximus felis convallis lacinia."
      "Phasellus at eros nisl. Etiam sit amet ex turpis. Sed nulla dolor, "
      "luctus et magna in, ornare condimentum augue. Ut tempus sit amet sapien "
      "sit amet pulvinar. Fusce in quam cursus turpis vulputate viverra eget "
      "non mauris. Vestibulum auctor pharetra faucibus. Sed odio risus, "
      "malesuada sit amet tincidunt vel, varius eget lectus. Pellentesque "
      "fringilla erat interdum, porttitor nisi ut, egestas ipsum. Nam eget "
      "augue at tellus rutrum vehicula. Cras ut erat augue."
      "Aliquam ornare facilisis nisl, eget scelerisque nulla rhoncus blandit. "
      "Donec gravida a diam vel sagittis. Nullam pharetra feugiat scelerisque. "
      "Mauris ornare pretium euismod. Mauris lacus orci, ullamcorper quis enim "
      "at, convallis suscipit massa. Sed suscipit odio dui, non tincidunt enim "
      "volutpat fringilla. Cras sit amet nunc velit. Nulla tempor venenatis "
      "malesuada. Proin porta eros sem, a efficitur felis auctor id. Phasellus "
      "bibendum neque sed metus viverra semper. Fusce vel rhoncus nisl. Nullam "
      "mollis erat eu felis malesuada iaculis. Maecenas tincidunt erat vitae "
      "purus sagittis, nec faucibus felis dignissim."
      "Orci varius natoque penatibus et magnis dis parturient montes, nascetur "
      "ridiculus mus. Praesent tristique ligula elementum justo mollis, eget "
      "efficitur elit viverra. Vestibulum a placerat ante, feugiat commodo "
      "nibh. Donec aliquet leo tempus, aliquam turpis a, imperdiet tellus. Sed "
      "auctor est eget volutpat dignissim. In facilisis sem quam, ut pulvinar "
      "neque pharetra id. Interdum et malesuada fames ac ante ipsum primis in "
      "faucibus. In mi enim, malesuada et feugiat eu, auctor quis ligula."
      "Nam ac augue nisi. Donec eget blandit purus. Aliquam pretium laoreet "
      "massa, eu commodo metus pellentesque non. Praesent elementum bibendum "
      "odio non congue. Nulla sed nisl sit amet metus porttitor condimentum. "
      "Mauris lacus sapien, ultrices in urna vitae, volutpat dignissim sapien. "
      "Vestibulum dictum egestas felis sit amet suscipit. Mauris eget diam "
      "consectetur, semper dolor eget, tincidunt ex. Nam vitae orci a mi "
      "vehicula ullamcorper. Proin scelerisque, nibh et vehicula egestas, eros "
      "dui posuere leo, ac dictum ligula leo vitae sem. Fusce tempor at ipsum "
      "nec commodo."
      "Praesent luctus sem diam, in eleifend sem suscipit non. Nam vestibulum "
      "ex felis, nec ornare nibh finibus vitae. Nulla et felis finibus, "
      "efficitur ipsum non, interdum nisl. Ut ut ex consectetur, cursus enim "
      "vel, vestibulum tellus. Aliquam tristique ullamcorper facilisis. Nulla "
      "facilisi. Fusce nulla nunc, pellentesque eu enim ac, lobortis maximus "
      "neque. Pellentesque in odio dignissim, vestibulum urna ac, finibus "
      "elit. Maecenas vitae dignissim libero. Donec magna velit, pellentesque "
      "eget pulvinar vel, scelerisque ut odio. Phasellus efficitur condimentum "
      "posuere. Fusce aliquam fermentum ex vitae porttitor. Integer aliquet "
      "mauris ut tincidunt blandit."
      "Fusce imperdiet elit vel congue gravida. Ut posuere eros non sem "
      "interdum fringilla. Praesent pulvinar sodales massa, ut vulputate ex "
      "bibendum et. Suspendisse pharetra elit in arcu egestas maximus. Aliquam "
      "nec metus dictum, fermentum justo in, aliquet lorem. Pellentesque "
      "egestas velit eu molestie eleifend. Nullam a ex odio. Nullam commodo "
      "velit mi, a convallis orci accumsan ac."
      "Mauris placerat diam id pretium pharetra. Pellentesque ut dictum nibh, "
      "in placerat diam. Nunc commodo turpis eget efficitur scelerisque. "
      "Suspendisse varius nibh at tellus porta consequat in vitae dui. "
      "Curabitur id ultrices arcu, ut tempor leo. Aenean sed augue nec turpis "
      "mattis gravida non sed arcu. Fusce a luctus ipsum, sed lacinia lorem. "
      "Donec sit amet nisl vestibulum ligula accumsan eleifend. Fusce non "
      "lorem condimentum, pharetra neque vel, tempus nisi. Donec id mauris "
      "gravida, consectetur sapien non, aliquam nunc."
      "Sed at eleifend orci. Cras at finibus tellus. Nullam porta tincidunt "
      "lobortis. Donec eget dolor lorem. Donec eget est ut augue maximus "
      "fringilla eu iaculis velit. Donec malesuada egestas varius. Aliquam "
      "ornare ligula a fermentum cursus. Nullam neque eros, accumsan quis "
      "dignissim quis, aliquet sit amet nulla. Integer sit amet nunc tempus, "
      "efficitur enim a, pretium arcu. Curabitur quis justo non mauris luctus "
      "posuere id eu est. Vestibulum volutpat, ipsum ac dictum condimentum, "
      "quam dui volutpat justo, vel tempor arcu risus ac enim. Nunc sit amet "
      "leo vel ex cursus tincidunt tristique et mauris. Morbi nec dignissim "
      "turpis, eget condimentum justo. Vestibulum semper varius varius. Cras "
      "in laoreet ipsum."
      "Aliquam tristique, ligula et accumsan elementum, risus ligula "
      "condimentum urna, bibendum posuere velit eros non enim. Aliquam ligula "
      "lectus, viverra nec egestas vitae, congue id elit. Nullam lobortis "
      "magna et dapibus scelerisque. Etiam egestas mollis risus eget "
      "sollicitudin. Vestibulum sed feugiat justo. Duis hendrerit dolor nunc, "
      "non consectetur diam lacinia ac. Curabitur porttitor aliquet tellus, "
      "eget rhoncus eros vehicula nec. Aliquam fermentum turpis at tellus "
      "varius, at eleifend nisl tempor. Pellentesque viverra luctus elit ac "
      "faucibus. Ut sit amet eleifend mi. Vivamus pretium magna nisl, nec "
      "condimentum turpis pellentesque sed. Aenean a tempus urna, non "
      "imperdiet purus. Donec vestibulum ante sed maximus finibus. Maecenas "
      "congue, erat sit amet lacinia dignissim, diam nibh porttitor dui, non "
      "lacinia lacus metus vulputate sem."
      "Nam accumsan nibh turpis, id tincidunt arcu rhoncus quis. Phasellus "
      "feugiat accumsan convallis. Nunc tristique erat dui, maximus "
      "ullamcorper neque laoreet eu. Proin enim metus, mattis sed odio id, "
      "ultrices tincidunt ipsum. In egestas consectetur odio posuere viverra. "
      "Maecenas neque lectus, pharetra hendrerit erat ac, eleifend sodales "
      "ante. Aenean velit nunc, tincidunt vel erat a, sagittis aliquam tortor."
      "Nam a tortor et ipsum consectetur interdum sed nec libero. Cras "
      "condimentum efficitur enim. Quisque faucibus, nunc vitae porttitor "
      "scelerisque, ex lorem elementum diam, sed condimentum urna dolor nec "
      "mauris. Nam scelerisque commodo justo a luctus. Quisque massa purus, "
      "sagittis vitae erat nec, ullamcorper posuere orci. Duis fermentum "
      "tellus turpis, quis congue justo facilisis ac. Donec elit quam, "
      "placerat sed pellentesque ut, interdum ut neque. Duis id quam ultrices, "
      "dapibus quam ornare, ullamcorper quam. Phasellus consequat mauris sed "
      "accumsan egestas. Donec maximus arcu eu vestibulum facilisis. Aliquam "
      "posuere porttitor orci. Nam facilisis, tortor vel tristique "
      "consectetur, enim erat pulvinar ligula, ac suscipit mauris magna nec "
      "ipsum. Donec facilisis quam vitae mi hendrerit, sodales finibus justo "
      "vestibulum. Praesent ultrices odio mauris, ut auctor ligula rutrum "
      "quis. Mauris eleifend feugiat felis eget vulputate. Etiam lacinia nec "
      "magna ut semper."
      "Vestibulum lacus tortor, volutpat in nulla quis, lacinia fringilla "
      "felis. Curabitur non risus sed diam tincidunt commodo. Suspendisse quis "
      "semper arcu. Nunc id efficitur tellus. Proin leo diam, ultricies eu "
      "purus mattis, faucibus congue ipsum. Aliquam ac pellentesque ipsum. In "
      "blandit odio at consequat malesuada. Duis eu ullamcorper lacus."
      "Nam id pretium erat. Curabitur vestibulum pulvinar nibh ut auctor. "
      "Vestibulum nec lorem eget lorem consectetur viverra non eget orci. Cras "
      "ac nunc turpis. Donec eget sapien euismod, consectetur diam ut, aliquet "
      "odio. Duis mauris metus, fringilla vitae mattis id, sollicitudin vitae "
      "sapien. Pellentesque at feugiat ex."
      "Nam quis tellus eget sem egestas venenatis. Vestibulum a dictum erat. "
      "Praesent aliquam lectus maximus tellus aliquam, mollis feugiat sem "
      "vestibulum. Aenean nec arcu neque. Fusce tincidunt mi massa, eget "
      "auctor nulla vestibulum sed. Integer convallis ligula risus, eu "
      "elementum dui pellentesque et. Donec lacus dolor, imperdiet sed nibh "
      "ut, sodales aliquet mi."
      "Sed cursus pulvinar est, id commodo quam faucibus sit amet. Nunc neque "
      "augue, porttitor rhoncus purus a, accumsan tempus nisi. Suspendisse "
      "potenti. Vestibulum pulvinar nunc enim. Nullam porttitor tempor "
      "dignissim. Maecenas blandit velit nec tincidunt congue. Proin sed "
      "rutrum justo. Etiam convallis magna purus, eu porttitor eros "
      "pellentesque cursus. Nulla auctor ex quis interdum venenatis."
      "Nullam et malesuada metus. Aenean imperdiet sollicitudin felis, sed "
      "suscipit arcu ultrices ut. Suspendisse potenti. Suspendisse dapibus at "
      "nisl blandit aliquet. Pellentesque habitant morbi tristique senectus et "
      "netus et malesuada fames ac turpis egestas. Ut rhoncus odio eget "
      "aliquet varius. Aliquam vulputate dolor in leo sagittis, a congue diam "
      "gravida. Cras dignissim est ex, in sodales neque dictum non. Curabitur "
      "hendrerit posuere risus vel molestie. Curabitur scelerisque lorem "
      "porttitor ex auctor faucibus. Nunc placerat est laoreet mauris mattis, "
      "ornare vehicula ipsum eleifend."
      "Nullam venenatis nec mi eu tincidunt. Nam ultrices lacus nibh, vel "
      "facilisis sapien molestie nec. Donec euismod iaculis euismod. Morbi "
      "eros ex, sodales id nunc lobortis, interdum euismod velit. Etiam eget "
      "sem sed metus molestie tristique et in est. Aliquam sollicitudin sapien "
      "ut tortor lobortis sagittis. Praesent facilisis convallis congue. "
      "Vestibulum volutpat quam quis hendrerit tincidunt. Integer in nisi "
      "nibh. Morbi blandit nibh non pretium porta."
      "Cras a malesuada lacus, nec efficitur est. Integer faucibus enim at "
      "sapien mollis tempor. Pellentesque quis arcu tempor eros feugiat "
      "bibendum porttitor ut urna. In interdum metus tortor, eget aliquet erat "
      "vulputate feugiat. Quisque fermentum turpis vitae diam molestie, ac "
      "commodo risus pretium. Cras tristique libero et porta tincidunt. Mauris "
      "cursus iaculis ante, quis imperdiet leo fermentum feugiat. Cras rutrum "
      "interdum nisi, id viverra leo elementum tincidunt. Suspendisse magna "
      "dui, lacinia sed diam id, convallis feugiat tortor. Aenean nulla elit, "
      "accumsan id imperdiet non, pulvinar sit amet ante. Duis aliquet odio "
      "vel imperdiet auctor. Sed eu dui sit amet nulla gravida rutrum auctor "
      "eu risus. Vivamus tempus vel enim non sagittis."
      "Vestibulum massa tortor, interdum eget orci vitae, condimentum dapibus "
      "nisl. Etiam convallis sapien sit amet metus varius aliquet. Praesent "
      "ultrices massa id facilisis tincidunt. Vestibulum blandit commodo "
      "placerat. Aliquam erat volutpat. Praesent elementum lacus et mauris "
      "pulvinar aliquam. Nulla facilisi. Sed eget vulputate sapien. Sed nec "
      "suscipit arcu. Phasellus sodales nunc vel porta rutrum. Nulla vulputate "
      "dolor eu sapien posuere, non laoreet enim dapibus. Donec sed eros non "
      "nisl porta tristique. Pellentesque lectus mauris, vehicula ut ornare "
      "vitae, iaculis vitae ex. Ut vestibulum, diam eu finibus dapibus, tortor "
      "velit congue urna, id finibus mi lectus sit amet ante."
      "Nam pellentesque nisl orci, eu facilisis augue faucibus at. Maecenas "
      "diam lacus, cursus ut dui vitae, semper pellentesque elit. Quisque "
      "suscipit, arcu et tristique placerat, turpis orci bibendum purus, sit "
      "amet posuere risus eros a dui. Nunc bibendum libero sed lobortis "
      "consectetur. In blandit tellus ac mattis euismod. Donec laoreet commodo "
      "dui fringilla consequat. Nam ornare lobortis ornare."
      "Nunc eu ultrices tortor, at suscipit erat. Nulla rhoncus ex eu neque "
      "mollis, quis vehicula massa tincidunt. Nulla a dictum ex. Maecenas "
      "posuere lacus libero, ut laoreet nisi dictum quis. Nullam sed dolor "
      "pulvinar, congue tellus ullamcorper, faucibus tellus. Suspendisse "
      "sollicitudin risus eu dui iaculis cursus. Nam vulputate, purus et "
      "vulputate suscipit, nibh ipsum aliquet sem, nec semper orci felis sed "
      "magna. Nulla placerat egestas tristique."
      "Curabitur maximus risus ipsum, et viverra velit malesuada vitae. Sed ut "
      "mauris nisl. Sed ut urna dui. Mauris ullamcorper dui vel risus sodales, "
      "vitae porta massa pulvinar. Proin cursus interdum mi, eget placerat "
      "erat efficitur vel. Donec et elit ut augue fringilla blandit. Proin "
      "pellentesque erat sit amet auctor varius. Sed ligula tellus, imperdiet "
      "ac luctus sed, tincidunt sed eros. Donec tempus nisi eu mi elementum "
      "porta. Curabitur in arcu sodales, dignissim massa sed, eleifend nisi. "
      "Vivamus convallis vestibulum leo nec iaculis. Duis libero orci, viverra "
      "in quam vel, porttitor facilisis magna. Suspendisse eu urna est. Nam "
      "dapibus urna vitae metus sodales, mollis tempor diam bibendum. "
      "Pellentesque venenatis dui at nunc tincidunt laoreet. Mauris a egestas "
      "leo."
      "Vivamus gravida libero ultrices eros luctus, vitae vulputate ipsum "
      "lobortis. Nulla maximus venenatis vulputate. Nullam non rutrum ante, "
      "vel euismod tortor. Quisque non ante vehicula, iaculis ligula sit amet, "
      "dapibus turpis. Quisque eget ligula nisl. Quisque ac finibus nunc. "
      "Maecenas a imperdiet nisi. Cras sagittis libero ipsum, feugiat "
      "tincidunt augue mattis sed. Nunc dictum massa vel velit semper "
      "venenatis eget nec urna. Curabitur eros mi, scelerisque eget metus at, "
      "hendrerit commodo eros. Nulla ut convallis justo. Vivamus elementum "
      "eleifend mauris, et sodales eros malesuada ut. Aenean in molestie "
      "massa. Maecenas ut eros justo."
      "Cras tempus neque at fermentum mattis. Donec dignissim metus risus, sit "
      "amet tincidunt tellus efficitur quis. Fusce condimentum, mi ac "
      "convallis dapibus, urna enim placerat nunc, quis suscipit enim sem sit "
      "amet velit. Pellentesque vel nibh non est scelerisque suscipit. Mauris "
      "pellentesque tellus pretium justo elementum, at mollis nulla volutpat. "
      "Suspendisse volutpat dolor ut tortor congue, non porta ipsum interdum. "
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices "
      "posuere cubilia Curae;"
      "Praesent et nisl ipsum. Curabitur a faucibus lacus, et tristique "
      "tortor. Donec pharetra tortor non magna iaculis laoreet. Cras sed nisl "
      "nec nunc ornare volutpat. Proin quis porta augue. Morbi neque mi, "
      "mattis sed ligula sed, blandit maximus nunc. Donec mattis metus eget ex "
      "porttitor fermentum."
      "Vestibulum pellentesque tempor urna at cursus. Maecenas lacus erat, "
      "tincidunt vel vehicula in, lacinia ut enim. Nullam volutpat lobortis "
      "suscipit. Ut vel maximus neque. Integer venenatis justo ante, eget "
      "lobortis nisl tempus eu. Duis sollicitudin mauris ac porttitor "
      "tristique. Integer sed libero libero. Sed pretium maximus mi, quis "
      "semper purus varius vel. Donec metus odio, elementum vitae nibh quis, "
      "ullamcorper tincidunt diam."
      "Nunc lacus erat, facilisis vitae nisi ac, mattis convallis diam. Nullam "
      "placerat metus ut sapien condimentum venenatis. Pellentesque quis nibh "
      "scelerisque, malesuada nisi at, venenatis mauris. Integer euismod "
      "dictum libero eu scelerisque. Aliquam in efficitur lectus. Vestibulum "
      "elit felis, ornare id dui id, pellentesque lacinia mauris. Pellentesque "
      "accumsan interdum massa, id eleifend elit finibus ac. Ut pharetra arcu "
      "non lectus molestie, ac tempor massa scelerisque. Phasellus varius "
      "blandit mauris, vitae pretium turpis convallis sit amet. Sed congue at "
      "ipsum eget efficitur. Integer ut felis ante. Duis ut lacinia lorem. "
      "Proin viverra bibendum nunc id scelerisque. Sed gravida eros quis dui "
      "pretium tincidunt."
      "Suspendisse potenti. Donec ultrices eu massa vitae elementum. "
      "Pellentesque sed tellus a enim pharetra fermentum. Quisque enim lorem, "
      "malesuada nec ante eget, malesuada gravida diam. Etiam convallis ac dui "
      "nec blandit. Aenean odio risus, lacinia in mattis tempus, semper a "
      "diam. Suspendisse potenti. Curabitur feugiat porta auctor. Nulla quam "
      "urna, pellentesque sit amet sapien id, euismod scelerisque massa. Fusce "
      "id mauris hendrerit enim sagittis congue sit amet non risus."
      "Pellentesque non venenatis felis. Quisque pharetra sit amet orci vel "
      "euismod. Nullam diam augue, molestie ac finibus sit amet, imperdiet ut "
      "velit. Nullam tincidunt mollis mi, at suscipit augue scelerisque non. "
      "Pellentesque facilisis blandit dui, ut sollicitudin tortor pretium ut. "
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse "
      "vehicula, sapien a pellentesque pharetra, erat eros maximus neque, et "
      "luctus mauris nibh vel lorem. Proin dignissim tincidunt velit et "
      "auctor. In hac habitasse platea dictumst. Fusce eget turpis nulla."
      "Pellentesque mollis purus sed risus placerat malesuada. Integer "
      "volutpat, enim quis sodales tincidunt, velit orci ullamcorper quam, sed "
      "interdum felis ex id dui. Nullam vel imperdiet nisi. Cras condimentum "
      "ut ex quis pellentesque. Nunc et eleifend tortor. Ut fringilla est ac "
      "porttitor aliquet. Donec elementum urna non dui gravida, quis varius "
      "purus imperdiet. Maecenas mauris arcu, sodales sed volutpat id, congue "
      "in mauris. Suspendisse vel libero quis tellus mollis ornare. Proin "
      "porta est nisl, id fringilla magna interdum in."
      "Mauris tortor libero, tristique sit amet enim quis, euismod auctor "
      "velit. Integer ornare pellentesque consectetur. Sed viverra massa vel "
      "placerat sollicitudin. Nam luctus lobortis justo, sit amet varius urna "
      "efficitur quis. Sed a felis vel sapien luctus porta ut vel massa. Proin "
      "commodo libero et tincidunt dignissim. Duis in iaculis libero, et "
      "dapibus magna. Nulla sit amet mattis magna, quis faucibus justo. "
      "Vivamus luctus aliquam nulla a condimentum. Maecenas lacinia neque "
      "lacus, at interdum neque pharetra ac. Fusce viverra purus nibh, sit "
      "amet gravida nisl scelerisque et."
      "Duis nec purus augue. Etiam volutpat volutpat enim, non congue neque "
      "dignissim sed. Ut commodo leo at dui cursus ultrices. Nullam in lacinia "
      "neque, efficitur aliquet eros. Suspendisse vitae aliquet mi. "
      "Pellentesque eget hendrerit diam. Phasellus sollicitudin auctor arcu "
      "nec tristique."
      "Etiam tristique mi sit amet tellus ullamcorper dignissim. Aenean vel "
      "orci nunc. Etiam molestie, velit ut elementum accumsan, turpis odio "
      "tristique tortor, at condimentum arcu tellus in risus. Vivamus "
      "dignissim risus et tortor tincidunt, et malesuada nisi posuere. Ut nec "
      "facilisis enim, quis faucibus dui. Nunc sagittis cursus est, a "
      "facilisis massa sodales ac. Integer elementum est nec risus accumsan "
      "pharetra. Nam vulputate leo nec nulla placerat, ut ultricies purus "
      "accumsan."
      "Donec sed elit nec ex scelerisque semper. Quisque neque purus, gravida "
      "sit amet eleifend non, molestie eget ante. Pellentesque auctor turpis "
      "et mi posuere, id fringilla nibh tempor. Vivamus scelerisque tincidunt "
      "ipsum, in scelerisque tortor congue a. Duis a lobortis justo. Nam vitae "
      "nisi imperdiet, venenatis velit non, pretium lectus. Pellentesque "
      "habitant morbi tristique senectus et netus et malesuada fames ac turpis "
      "egestas. Sed semper velit vitae tellus tristique, in vulputate eros "
      "vestibulum."
      "Phasellus eget tortor eu quam laoreet porttitor ac at purus. Maecenas "
      "ac nisl tellus. Sed varius sapien quis metus blandit, pretium varius "
      "ante varius. Pellentesque ac est ut leo bibendum rhoncus. Proin sapien "
      "magna, aliquam eu pretium a, venenatis et purus. Morbi pulvinar elit "
      "non convallis mattis. Quisque iaculis vestibulum sem. Vivamus tristique "
      "lacus ut ipsum auctor hendrerit. Etiam porta diam odio, eu accumsan "
      "nibh tincidunt quis. Quisque diam dui, accumsan sed egestas et, dictum "
      "et dolor. Donec sollicitudin tempor eros, at feugiat ipsum ultricies "
      "in. Proin at est sagittis, interdum enim quis, ultrices diam. Praesent "
      "sagittis eget lectus eu dictum. Ut ut sapien imperdiet, bibendum tellus "
      "ut, ullamcorper lectus. Mauris odio est, pellentesque quis ante quis, "
      "rhoncus interdum eros."
      "Etiam elit enim, vehicula in diam at, lacinia finibus nisi. Etiam "
      "sollicitudin nunc a pharetra blandit. Integer sodales sollicitudin "
      "mattis. Nulla sem arcu, tempus sed elit ut, auctor accumsan arcu. Donec "
      "consectetur vulputate ornare. Praesent porttitor, orci eu pulvinar "
      "tristique, dolor erat tempus nibh, ut dictum ipsum libero at enim. "
      "Fusce volutpat magna quis est venenatis dictum. Suspendisse facilisis "
      "sed nibh ac varius. Donec tempor sit amet risus sit amet pretium. Proin "
      "auctor justo urna, vel aliquam nunc placerat fermentum. Nam in mollis "
      "eros."
      "Mauris sed nulla in sem pulvinar pulvinar. Cras id commodo velit. In "
      "hac habitasse platea dictumst. Ut in scelerisque leo. Vestibulum "
      "dignissim, mauris at ornare iaculis, sapien sem efficitur magna, et "
      "lobortis lorem tortor nec tellus. Aliquam erat volutpat. Nam facilisis, "
      "purus hendrerit lacinia porta, urna sapien pellentesque nunc, a tempus "
      "sem nulla vitae sem. Duis ultrices rhoncus mauris, vitae efficitur nisl "
      "congue sit amet. Integer sed est ac elit tempor vehicula eu vel tortor. "
      "Etiam mi urna, auctor elementum efficitur sit amet, scelerisque et "
      "ipsum."
      "Nam elementum ut tellus id sodales. Suspendisse aliquam at urna ornare "
      "facilisis. Ut auctor ullamcorper ex, at finibus massa tempus non. Cras "
      "tempor efficitur nulla in blandit. Aliquam at orci varius, pretium "
      "risus sed, vehicula diam. Suspendisse eu arcu sed nisl bibendum feugiat "
      "ac at erat. Aliquam erat volutpat. Suspendisse suscipit turpis quam, "
      "sed lacinia ligula luctus non. Aliquam turpis odio, accumsan vel ante "
      "sit amet, dictum bibendum leo. In hac habitasse platea dictumst. "
      "Suspendisse at metus non sapien sagittis lobortis. Sed sagittis diam a "
      "imperdiet gravida. Maecenas nec ipsum quis erat pellentesque tincidunt."
      "Maecenas non sem ac nisl tempor pulvinar at eu elit. Nullam rutrum "
      "sapien a elit tempus, sed feugiat quam lobortis. Mauris eget blandit "
      "metus. Cras ac luctus arcu. Class aptent taciti sociosqu ad litora "
      "torquent per conubia nostra, per inceptos himenaeos. Sed nec leo "
      "ligula. Morbi aliquam, justo in porta eleifend, quam mauris elementum "
      "augue, eget dignissim orci metus non massa. Vestibulum euismod velit "
      "volutpat augue placerat, et scelerisque erat aliquam. Orci varius "
      "natoque penatibus et magnis dis parturient montes, nascetur ridiculus "
      "mus. Integer gravida lobortis dictum. Etiam ex magna, congue id sem "
      "quis, mattis euismod metus. Nulla eget odio et dui feugiat tincidunt "
      "vel id lacus. Pellentesque iaculis pharetra lectus nec rutrum. Ut "
      "venenatis at nisl quis malesuada. Vivamus mattis malesuada leo id "
      "scelerisque."
      "Fusce venenatis elementum nulla, sed commodo eros volutpat eget. "
      "Pellentesque et tortor maximus, ultrices urna vel, consequat massa. Sed "
      "eget ipsum eget odio cursus lacinia nec sit amet erat. Nulla facilisi. "
      "Fusce rhoncus sem ac mi malesuada feugiat. In volutpat vel orci et "
      "tincidunt. Aliquam erat volutpat. Pellentesque habitant morbi tristique "
      "senectus et netus et malesuada fames ac turpis egestas. Sed odio nulla, "
      "tempus quis blandit ut, venenatis et erat. Suspendisse varius mauris "
      "sed quam facilisis, id gravida velit volutpat. Praesent nec lorem "
      "laoreet, accumsan leo in, rhoncus ex. Cras lorem dui, laoreet ut magna "
      "eu, facilisis efficitur nulla. Mauris nulla nunc, commodo non velit "
      "euismod, posuere tristique mauris. Aliquam faucibus ante eu magna "
      "viverra, sed convallis risus aliquam. Sed a justo a nisi fermentum "
      "varius in quis purus."
      "Vestibulum ultrices nulla quam, eu posuere dui accumsan quis. Praesent "
      "vel sagittis risus. Praesent tristique magna a sem blandit, ac maximus "
      "eros vulputate. Praesent massa ligula, tempus nec lacus vel, posuere "
      "viverra metus. Donec sed libero ligula. Vivamus vitae ipsum convallis "
      "justo venenatis euismod sed in libero. Quisque cursus feugiat dui eu "
      "aliquet. Cras feugiat efficitur nisi, vel tincidunt risus condimentum "
      "id. Donec sagittis, dui nec tincidunt mollis, sem nulla cursus ante, "
      "accumsan bibendum ipsum justo et urna."
      "Fusce non vehicula purus, ut tincidunt augue. Proin pretium interdum "
      "interdum. Etiam semper ultricies quam. Vivamus auctor mi pharetra felis "
      "commodo, non fringilla orci mattis. Aliquam in elementum metus, sit "
      "amet vehicula sapien. Quisque consequat aliquet feugiat. Sed augue "
      "magna, aliquam non libero et, accumsan finibus leo."
      "Fusce rhoncus, urna et imperdiet dictum, est magna efficitur nunc, non "
      "vestibulum nunc orci id purus. Pellentesque habitant morbi tristique "
      "senectus et netus et malesuada fames ac turpis egestas. Mauris est "
      "nisi, vulputate commodo nisl ac, rutrum ultrices orci. Fusce dictum "
      "rhoncus libero. Curabitur turpis massa, suscipit eu fringilla "
      "elementum, dictum ac dui. Ut euismod consequat sapien, lobortis "
      "placerat orci sagittis non. Nulla viverra erat quam, vitae luctus felis "
      "faucibus a. Integer et malesuada massa. Morbi sit amet magna eleifend, "
      "cursus libero non, egestas nisi. Maecenas posuere id magna et "
      "venenatis. In dapibus, elit vel iaculis fermentum, purus lectus aliquam "
      "dui, et congue nulla turpis vel arcu. Curabitur posuere blandit "
      "aliquam. Fusce sit amet convallis felis. Sed maximus, urna condimentum "
      "malesuada pretium, nunc dolor dignissim magna, sed ornare sapien velit "
      "sed enim. Integer congue, orci ac aliquet fermentum, magna erat viverra "
      "justo, at feugiat massa odio id elit. Nunc a nisi felis."
      "Nullam hendrerit ultricies augue vel ullamcorper. Fusce elementum "
      "dapibus massa. Nulla facilisi. Donec sapien ante, aliquet et odio non, "
      "fringilla interdum mi. Phasellus vel placerat nisi. Cras ut pulvinar "
      "enim. Nunc eu quam nec nisl sodales elementum vel a nulla. Cras "
      "porttitor, ante in iaculis lobortis, quam arcu pretium ante, "
      "consectetur pretium nulla odio at lacus. Ut molestie non nisi posuere "
      "suscipit. Vivamus in pellentesque sapien. Aenean placerat diam at lorem "
      "euismod, a fringilla erat luctus. In hac habitasse platea dictumst."
      "Nam commodo tortor vehicula ipsum consequat vulputate. Fusce ultrices "
      "arcu sapien, nec vulputate est sollicitudin non. Suspendisse non orci "
      "pulvinar, dictum ex in, viverra sem. Sed consectetur, massa varius "
      "viverra ultricies, erat arcu commodo libero, a auctor lorem leo varius "
      "eros. Aliquam nec sollicitudin leo, sit amet iaculis dolor. "
      "Pellentesque suscipit rhoncus velit, ac cursus neque facilisis tempus. "
      "Nulla laoreet varius lectus et consequat. Sed ornare egestas enim in "
      "viverra."
      "Morbi ut interdum magna. Nullam purus elit, varius a imperdiet id, "
      "accumsan vitae quam. Ut blandit lacus massa, quis pretium ipsum semper "
      "et. Nulla fringilla semper sagittis. Duis pretium placerat velit, eget "
      "scelerisque augue pretium quis. Vivamus sem dolor, condimentum ut "
      "hendrerit non, placerat id leo. Fusce sit amet orci nec elit tincidunt "
      "dignissim at non ex. Nulla sed cursus augue. Nullam in tempus est. "
      "Pellentesque vel bibendum sapien. Donec dictum eleifend placerat. "
      "Integer rhoncus ex vel tristique gravida."
      "Vestibulum feugiat massa sapien, tincidunt sagittis magna tristique in. "
      "Aenean nunc orci, mattis quis tempor ac, lobortis at nulla. In in magna "
      "a nulla ultrices ornare id ut enim. Aenean dignissim ligula in orci "
      "semper dapibus. Sed eu consectetur ante. Sed a arcu rhoncus ante "
      "sagittis tristique. Aliquam erat volutpat. Vestibulum ullamcorper "
      "egestas mauris id ultrices. Fusce cursus ut nunc a finibus. Praesent "
      "gravida quam diam, et maximus mauris suscipit ac."
      "Sed pretium luctus leo, ut bibendum massa luctus vel. Vestibulum eu "
      "massa consectetur, ullamcorper diam vitae, sodales felis. Mauris "
      "blandit tortor quis est tincidunt, eu laoreet dolor blandit. Maecenas "
      "convallis convallis fermentum. Morbi sit amet leo scelerisque, "
      "elementum nisi a, dictum ex. Duis vel risus feugiat, commodo tellus "
      "sed, ultrices ipsum. Aenean id odio leo. Proin viverra purus vestibulum "
      "urna tincidunt convallis. Pellentesque tempus aliquam lacus, in varius "
      "massa pellentesque in. Proin semper eros et nisi varius, quis bibendum "
      "velit semper. Donec cursus libero at urna iaculis, sed tempus velit "
      "hendrerit. Curabitur sit amet ultrices odio. In eleifend, elit nec "
      "rutrum varius, ante felis imperdiet velit, sit amet hendrerit lorem dui "
      "ac lacus. Phasellus ante massa, ornare in odio non, congue pellentesque "
      "est. Quisque rutrum purus nec diam convallis, eu pulvinar elit "
      "fringilla."
      "Nunc laoreet in erat sit amet auctor. Cras rhoncus sit amet tellus id "
      "facilisis. In accumsan risus magna, nec hendrerit lacus hendrerit eget. "
      "Ut aliquet molestie maximus. Vivamus sollicitudin et nulla nec "
      "volutpat. Ut sed lacus sed urna varius elementum sed vitae tortor. "
      "Praesent in ultricies tortor, eu vehicula quam. Pellentesque nibh mi, "
      "sodales a metus placerat, efficitur condimentum turpis. In ut nisl nec "
      "lacus malesuada fringilla a ac odio. Morbi viverra euismod consectetur. "
      "Nam aliquet sodales odio vitae facilisis. Nullam eu fermentum ligula. "
      "Donec mollis vestibulum nibh at aliquet. Maecenas ut libero et nulla "
      "feugiat porttitor. Praesent vehicula justo nec lorem ornare blandit. "
      "Nunc quis dapibus orci.";

  const std::string expected =
      "orci. dapibus quis Nunc blandit. ornare lorem nec justo vehicula "
      "Praesent porttitor. feugiat nulla et libero ut Maecenas aliquet. at "
      "nibh vestibulum mollis Donec ligula. fermentum eu Nullam facilisis. "
      "vitae odio sodales aliquet Nam consectetur. euismod viverra Morbi odio. "
      "ac a fringilla malesuada lacus nec nisl ut In turpis. condimentum "
      "efficitur placerat, metus a sodales mi, nibh Pellentesque quam. "
      "vehicula eu tortor, ultricies in Praesent tortor. vitae sed elementum "
      "varius urna sed lacus sed Ut volutpat. nec nulla et sollicitudin "
      "Vivamus maximus. molestie aliquet Ut eget. hendrerit lacus hendrerit "
      "nec magna, risus accumsan In facilisis. id tellus amet sit rhoncus Cras "
      "auctor. amet sit erat in laoreet fringilla.Nunc elit pulvinar eu "
      "convallis, diam nec purus rutrum Quisque est. pellentesque congue non, "
      "odio in ornare massa, ante Phasellus lacus. ac dui lorem hendrerit amet "
      "sit velit, imperdiet felis ante varius, rutrum nec elit eleifend, In "
      "odio. ultrices amet sit Curabitur hendrerit. velit tempus sed iaculis, "
      "urna at libero cursus Donec semper. velit bibendum quis varius, nisi et "
      "eros semper Proin in. pellentesque massa varius in lacus, aliquam "
      "tempus Pellentesque convallis. tincidunt urna vestibulum purus viverra "
      "Proin leo. odio id Aenean ipsum. ultrices sed, tellus commodo feugiat, "
      "risus vel Duis ex. dictum a, nisi elementum scelerisque, leo amet sit "
      "Morbi fermentum. convallis convallis Maecenas blandit. dolor laoreet eu "
      "tincidunt, est quis tortor blandit Mauris felis. sodales vitae, diam "
      "ullamcorper consectetur, massa eu Vestibulum vel. luctus massa bibendum "
      "ut leo, luctus pretium ac.Sed suscipit mauris maximus et diam, quam "
      "gravida Praesent finibus. a nunc ut cursus Fusce ultrices. id mauris "
      "egestas ullamcorper Vestibulum volutpat. erat Aliquam tristique. "
      "sagittis ante rhoncus arcu a Sed ante. consectetur eu Sed dapibus. "
      "semper orci in ligula dignissim Aenean enim. ut id ornare ultrices "
      "nulla a magna in In nulla. at lobortis ac, tempor quis mattis orci, "
      "nunc Aenean in. tristique magna sagittis tincidunt sapien, massa "
      "feugiat gravida.Vestibulum tristique vel ex rhoncus Integer placerat. "
      "eleifend dictum Donec sapien. bibendum vel Pellentesque est. tempus in "
      "Nullam augue. cursus sed Nulla ex. non at dignissim tincidunt elit nec "
      "orci amet sit Fusce leo. id placerat non, hendrerit ut condimentum "
      "dolor, sem Vivamus quis. pretium augue scelerisque eget velit, placerat "
      "pretium Duis sagittis. semper fringilla Nulla et. semper ipsum pretium "
      "quis massa, lacus blandit Ut quam. vitae accumsan id, imperdiet a "
      "varius elit, purus Nullam magna. interdum ut viverra.Morbi in enim "
      "egestas ornare Sed consequat. et lectus varius laoreet Nulla tempus. "
      "facilisis neque cursus ac velit, rhoncus suscipit Pellentesque dolor. "
      "iaculis amet sit leo, sollicitudin nec Aliquam eros. varius leo lorem "
      "auctor a libero, commodo arcu erat ultricies, viverra varius massa "
      "consectetur, Sed sem. viverra in, ex dictum pulvinar, orci non "
      "Suspendisse non. sollicitudin est vulputate nec sapien, arcu ultrices "
      "Fusce vulputate. consequat ipsum vehicula tortor commodo dictumst.Nam "
      "platea habitasse hac In luctus. erat fringilla a euismod, lorem at diam "
      "placerat Aenean sapien. pellentesque in Vivamus suscipit. posuere nisi "
      "non molestie Ut lacus. at odio nulla pretium consectetur ante, pretium "
      "arcu quam lobortis, iaculis in ante porttitor, Cras nulla. a vel "
      "elementum sodales nisl nec quam eu Nunc enim. pulvinar ut Cras nisi. "
      "placerat vel Phasellus mi. interdum fringilla non, odio et aliquet "
      "ante, sapien Donec facilisi. Nulla massa. dapibus elementum Fusce "
      "ullamcorper. vel augue ultricies hendrerit felis.Nullam nisi a Nunc "
      "elit. id odio massa feugiat at justo, viverra erat magna fermentum, "
      "aliquet ac orci congue, Integer enim. sed velit sapien ornare sed "
      "magna, dignissim dolor nunc pretium, malesuada condimentum urna "
      "maximus, Sed felis. convallis amet sit Fusce aliquam. blandit posuere "
      "Curabitur arcu. vel turpis nulla congue et dui, aliquam lectus purus "
      "fermentum, iaculis vel elit dapibus, In venenatis. et magna id posuere "
      "Maecenas nisi. egestas non, libero cursus eleifend, magna amet sit "
      "Morbi massa. malesuada et Integer a. faucibus felis luctus vitae quam, "
      "erat viverra Nulla non. sagittis orci placerat lobortis sapien, "
      "consequat euismod Ut dui. ac dictum elementum, fringilla eu suscipit "
      "massa, turpis Curabitur libero. rhoncus dictum Fusce orci. ultrices "
      "rutrum ac, nisl commodo vulputate nisi, est Mauris egestas. turpis ac "
      "fames malesuada et netus et senectus tristique morbi habitant "
      "Pellentesque purus. id orci nunc vestibulum non nunc, efficitur magna "
      "est dictum, imperdiet et urna rhoncus, leo.Fusce finibus accumsan et, "
      "libero non aliquam magna, augue Sed feugiat. aliquet consequat Quisque "
      "sapien. vehicula amet sit metus, elementum in Aliquam mattis. orci "
      "fringilla non commodo, felis pharetra mi auctor Vivamus quam. ultricies "
      "semper Etiam interdum. interdum pretium Proin augue. tincidunt ut "
      "purus, vehicula non urna.Fusce et justo ipsum bibendum accumsan ante, "
      "cursus nulla sem mollis, tincidunt nec dui sagittis, Donec id. "
      "condimentum risus tincidunt vel nisi, efficitur feugiat Cras aliquet. "
      "eu dui feugiat cursus Quisque libero. in sed euismod venenatis justo "
      "convallis ipsum vitae Vivamus ligula. libero sed Donec metus. viverra "
      "posuere vel, lacus nec tempus ligula, massa Praesent vulputate. eros "
      "maximus ac blandit, sem a magna tristique Praesent risus. sagittis vel "
      "Praesent quis. accumsan dui posuere eu quam, nulla ultrices "
      "purus.Vestibulum quis in varius fermentum nisi a justo a Sed aliquam. "
      "risus convallis sed viverra, magna eu ante faucibus Aliquam mauris. "
      "tristique posuere euismod, velit non commodo nunc, nulla Mauris nulla. "
      "efficitur facilisis eu, magna ut laoreet dui, lorem Cras ex. rhoncus "
      "in, leo accumsan laoreet, lorem nec Praesent volutpat. velit gravida id "
      "facilisis, quam sed mauris varius Suspendisse erat. et venenatis ut, "
      "blandit quis tempus nulla, odio Sed egestas. turpis ac fames malesuada "
      "et netus et senectus tristique morbi habitant Pellentesque volutpat. "
      "erat Aliquam tincidunt. et orci vel volutpat In feugiat. malesuada mi "
      "ac sem rhoncus Fusce facilisi. Nulla erat. amet sit nec lacinia cursus "
      "odio eget ipsum eget Sed massa. consequat vel, urna ultrices maximus, "
      "tortor et Pellentesque eget. volutpat eros commodo sed nulla, elementum "
      "venenatis scelerisque.Fusce id leo malesuada mattis Vivamus malesuada. "
      "quis nisl at venenatis Ut rutrum. nec lectus pharetra iaculis "
      "Pellentesque lacus. id vel tincidunt feugiat dui et odio eget Nulla "
      "metus. euismod mattis quis, sem id congue magna, ex Etiam dictum. "
      "lobortis gravida Integer mus. ridiculus nascetur montes, parturient dis "
      "magnis et penatibus natoque varius Orci aliquam. erat scelerisque et "
      "placerat, augue volutpat velit euismod Vestibulum massa. non metus orci "
      "dignissim eget augue, elementum mauris quam eleifend, porta in justo "
      "aliquam, Morbi ligula. leo nec Sed himenaeos. inceptos per nostra, "
      "conubia per torquent litora ad sociosqu taciti aptent Class arcu. "
      "luctus ac Cras metus. blandit eget Mauris lobortis. quam feugiat sed "
      "tempus, elit a sapien rutrum Nullam elit. eu at pulvinar tempor nisl ac "
      "sem non tincidunt.Maecenas pellentesque erat quis ipsum nec Maecenas "
      "gravida. imperdiet a diam sagittis Sed lobortis. sagittis sapien non "
      "metus at Suspendisse dictumst. platea habitasse hac In leo. bibendum "
      "dictum amet, sit ante vel accumsan odio, turpis Aliquam non. luctus "
      "ligula lacinia sed quam, turpis suscipit Suspendisse volutpat. erat "
      "Aliquam erat. at ac feugiat bibendum nisl sed arcu eu Suspendisse diam. "
      "vehicula sed, risus pretium varius, orci at Aliquam blandit. in nulla "
      "efficitur tempor Cras non. tempus massa finibus at ex, ullamcorper "
      "auctor Ut facilisis. ornare urna at aliquam Suspendisse sodales. id "
      "tellus ut elementum ipsum.Nam et scelerisque amet, sit efficitur "
      "elementum auctor urna, mi Etiam tortor. vel eu vehicula tempor elit ac "
      "est sed Integer amet. sit congue nisl efficitur vitae mauris, rhoncus "
      "ultrices Duis sem. vitae nulla sem tempus a nunc, pellentesque sapien "
      "urna porta, lacinia hendrerit purus facilisis, Nam volutpat. erat "
      "Aliquam tellus. nec tortor lorem lobortis et magna, efficitur sem "
      "sapien iaculis, ornare at mauris dignissim, Vestibulum leo. scelerisque "
      "in Ut dictumst. platea habitasse hac In velit. commodo id Cras "
      "pulvinar. pulvinar sem in nulla sed eros.Mauris mollis in Nam "
      "fermentum. placerat nunc aliquam vel urna, justo auctor Proin pretium. "
      "amet sit risus amet sit tempor Donec varius. ac nibh sed facilisis "
      "Suspendisse dictum. venenatis est quis magna volutpat Fusce enim. at "
      "libero ipsum dictum ut nibh, tempus erat dolor tristique, pulvinar eu "
      "orci porttitor, Praesent ornare. vulputate consectetur Donec arcu. "
      "accumsan auctor ut, elit sed tempus arcu, sem Nulla mattis. "
      "sollicitudin sodales Integer blandit. pharetra a nunc sollicitudin "
      "Etiam nisi. finibus lacinia at, diam in vehicula enim, elit eros.Etiam "
      "interdum rhoncus quis, ante quis pellentesque est, odio Mauris lectus. "
      "ullamcorper ut, tellus bibendum imperdiet, sapien ut Ut dictum. eu "
      "lectus eget sagittis Praesent diam. ultrices quis, enim interdum "
      "sagittis, est at Proin in. ultricies ipsum feugiat at eros, tempor "
      "sollicitudin Donec dolor. et dictum et, egestas sed accumsan dui, diam "
      "Quisque quis. tincidunt nibh accumsan eu odio, diam porta Etiam "
      "hendrerit. auctor ipsum ut lacus tristique Vivamus sem. vestibulum "
      "iaculis Quisque mattis. convallis non elit pulvinar Morbi purus. et "
      "venenatis a, pretium eu aliquam magna, sapien Proin rhoncus. bibendum "
      "leo ut est ac Pellentesque varius. ante varius pretium blandit, metus "
      "quis sapien varius Sed tellus. nisl ac Maecenas purus. at ac porttitor "
      "laoreet quam eu tortor eget vestibulum.Phasellus eros vulputate in "
      "tristique, tellus vitae velit semper Sed egestas. turpis ac fames "
      "malesuada et netus et senectus tristique morbi habitant Pellentesque "
      "lectus. pretium non, velit venenatis imperdiet, nisi vitae Nam justo. "
      "lobortis a Duis a. congue tortor scelerisque in ipsum, tincidunt "
      "scelerisque Vivamus tempor. nibh fringilla id posuere, mi et turpis "
      "auctor Pellentesque ante. eget molestie non, eleifend amet sit gravida "
      "purus, neque Quisque semper. scelerisque ex nec elit sed accumsan.Donec "
      "purus ultricies ut placerat, nulla nec leo vulputate Nam pharetra. "
      "accumsan risus nec est elementum Integer ac. sodales massa facilisis a "
      "est, cursus sagittis Nunc dui. faucibus quis enim, facilisis nec Ut "
      "posuere. nisi malesuada et tincidunt, tortor et risus dignissim Vivamus "
      "risus. in tellus arcu condimentum at tortor, tristique odio turpis "
      "accumsan, elementum ut velit molestie, Etiam nunc. orci vel Aenean "
      "dignissim. ullamcorper tellus amet sit mi tristique tristique.Etiam nec "
      "arcu auctor sollicitudin Phasellus diam. hendrerit eget Pellentesque "
      "mi. aliquet vitae Suspendisse eros. aliquet efficitur neque, lacinia in "
      "Nullam ultrices. cursus dui at leo commodo Ut sed. dignissim neque "
      "congue non enim, volutpat volutpat Etiam augue. purus nec et.Duis "
      "scelerisque nisl gravida amet sit nibh, purus viverra Fusce ac. "
      "pharetra neque interdum at lacus, neque lacinia Maecenas condimentum. a "
      "nulla aliquam luctus Vivamus justo. faucibus quis magna, mattis amet "
      "sit Nulla magna. dapibus et libero, iaculis in Duis dignissim. "
      "tincidunt et libero commodo Proin massa. vel ut porta luctus sapien vel "
      "felis a Sed quis. efficitur urna varius amet sit justo, lobortis luctus "
      "Nam sollicitudin. placerat vel massa viverra Sed consectetur. "
      "pellentesque ornare Integer velit. auctor euismod quis, enim amet sit "
      "tristique libero, tortor in.Mauris interdum magna fringilla id nisl, "
      "est porta Proin ornare. mollis tellus quis libero vel Suspendisse "
      "mauris. in congue id, volutpat sed sodales arcu, mauris Maecenas "
      "imperdiet. purus varius quis gravida, dui non urna elementum Donec "
      "aliquet. porttitor ac est fringilla Ut tortor. eleifend et Nunc "
      "pellentesque. quis ex ut condimentum Cras nisi. imperdiet vel Nullam "
      "dui. id ex felis interdum sed quam, ullamcorper orci velit tincidunt, "
      "sodales quis enim volutpat, Integer malesuada. placerat risus sed purus "
      "mollis nulla.Pellentesque turpis eget Fusce dictumst. platea habitasse "
      "hac In auctor. et velit tincidunt dignissim Proin lorem. vel nibh "
      "mauris luctus et neque, maximus eros erat pharetra, pellentesque a "
      "sapien vehicula, Suspendisse elit. adipiscing consectetur amet, sit "
      "dolor ipsum Lorem ut. pretium tortor sollicitudin ut dui, blandit "
      "facilisis Pellentesque non. scelerisque augue suscipit at mi, mollis "
      "tincidunt Nullam velit. ut imperdiet amet, sit finibus ac molestie "
      "augue, diam Nullam euismod. vel orci amet sit pharetra Quisque felis. "
      "venenatis non risus.Pellentesque non amet sit congue sagittis enim "
      "hendrerit mauris id Fusce massa. scelerisque euismod id, sapien amet "
      "sit pellentesque urna, quam Nulla auctor. porta feugiat Curabitur "
      "potenti. Suspendisse diam. a semper tempus, mattis in lacinia risus, "
      "odio Aenean blandit. nec dui ac convallis Etiam diam. gravida malesuada "
      "eget, ante nec malesuada lorem, enim Quisque fermentum. pharetra enim a "
      "tellus sed Pellentesque elementum. vitae massa eu ultrices Donec "
      "potenti. tincidunt.Suspendisse pretium dui quis eros gravida Sed "
      "scelerisque. id nunc bibendum viverra Proin lorem. lacinia ut Duis "
      "ante. felis ut Integer efficitur. eget ipsum at congue Sed amet. sit "
      "convallis turpis pretium vitae mauris, blandit varius Phasellus "
      "scelerisque. massa tempor ac molestie, lectus non arcu pharetra Ut ac. "
      "finibus elit eleifend id massa, interdum accumsan Pellentesque mauris. "
      "lacinia pellentesque id, dui id ornare felis, elit Vestibulum lectus. "
      "efficitur in Aliquam scelerisque. eu libero dictum euismod Integer "
      "mauris. venenatis at, nisi malesuada scelerisque, nibh quis "
      "Pellentesque venenatis. condimentum sapien ut metus placerat Nullam "
      "diam. convallis mattis ac, nisi vitae facilisis erat, lacus diam.Nunc "
      "tincidunt ullamcorper quis, nibh vitae elementum odio, metus Donec vel. "
      "varius purus semper quis mi, maximus pretium Sed libero. libero sed "
      "Integer tristique. porttitor ac mauris sollicitudin Duis eu. tempus "
      "nisl lobortis eget ante, justo venenatis Integer neque. maximus vel Ut "
      "suscipit. lobortis volutpat Nullam enim. ut lacinia in, vehicula vel "
      "tincidunt erat, lacus Maecenas cursus. at urna tempor pellentesque "
      "fermentum.Vestibulum porttitor ex eget metus mattis Donec nunc. maximus "
      "blandit sed, ligula sed mattis mi, neque Morbi augue. porta quis Proin "
      "volutpat. ornare nunc nec nisl sed Cras laoreet. iaculis magna non "
      "tortor pharetra Donec tortor. tristique et lacus, faucibus a Curabitur "
      "ipsum. nisl et Curae;Praesent cubilia posuere ultrices et luctus orci "
      "faucibus in primis ipsum ante Vestibulum interdum. ipsum porta non "
      "congue, tortor ut dolor volutpat Suspendisse volutpat. nulla mollis at "
      "elementum, justo pretium tellus pellentesque Mauris suscipit. "
      "scelerisque est non nibh vel Pellentesque velit. amet sit sem enim "
      "suscipit quis nunc, placerat enim urna dapibus, convallis ac mi "
      "condimentum, Fusce quis. efficitur tellus tincidunt amet sit risus, "
      "metus dignissim Donec mattis. fermentum at neque tempus justo.Cras eros "
      "ut Maecenas massa. molestie in Aenean ut. malesuada eros sodales et "
      "mauris, eleifend elementum Vivamus justo. convallis ut Nulla eros. "
      "commodo hendrerit at, metus eget scelerisque mi, eros Curabitur urna. "
      "nec eget venenatis semper velit vel massa dictum Nunc sed. mattis augue "
      "tincidunt feugiat ipsum, libero sagittis Cras nisi. imperdiet a "
      "Maecenas nunc. finibus ac Quisque nisl. ligula eget Quisque turpis. "
      "dapibus amet, sit ligula iaculis vehicula, ante non Quisque tortor. "
      "euismod vel ante, rutrum non Nullam vulputate. venenatis maximus Nulla "
      "lobortis. ipsum vulputate vitae luctus, eros ultrices libero gravida "
      "leo.Vivamus egestas a Mauris laoreet. tincidunt nunc at dui venenatis "
      "Pellentesque bibendum. diam tempor mollis sodales, metus vitae urna "
      "dapibus Nam est. urna eu Suspendisse magna. facilisis porttitor vel, "
      "quam in viverra orci, libero Duis iaculis. nec leo vestibulum convallis "
      "Vivamus nisi. eleifend sed, massa dignissim sodales, arcu in Curabitur "
      "porta. elementum mi eu nisi tempus Donec eros. sed tincidunt sed, "
      "luctus ac imperdiet tellus, ligula Sed varius. auctor amet sit erat "
      "pellentesque Proin blandit. fringilla augue ut elit et Donec vel. "
      "efficitur erat placerat eget mi, interdum cursus Proin pulvinar. massa "
      "porta vitae sodales, risus vel dui ullamcorper Mauris dui. urna ut Sed "
      "nisl. mauris ut Sed vitae. malesuada velit viverra et ipsum, risus "
      "maximus tristique.Curabitur egestas placerat Nulla magna. sed felis "
      "orci semper nec sem, aliquet ipsum nibh suscipit, vulputate et purus "
      "vulputate, Nam cursus. iaculis dui eu risus sollicitudin Suspendisse "
      "tellus. faucibus ullamcorper, tellus congue pulvinar, dolor sed Nullam "
      "quis. dictum nisi laoreet ut libero, lacus posuere Maecenas ex. dictum "
      "a Nulla tincidunt. massa vehicula quis mollis, neque eu ex rhoncus "
      "Nulla erat. suscipit at tortor, ultrices eu ornare.Nunc lobortis ornare "
      "Nam consequat. fringilla dui commodo laoreet Donec euismod. mattis ac "
      "tellus blandit In consectetur. lobortis sed libero bibendum Nunc dui. a "
      "eros risus posuere amet sit purus, bibendum orci turpis placerat, "
      "tristique et arcu suscipit, Quisque elit. pellentesque semper vitae, "
      "dui ut cursus lacus, diam Maecenas at. faucibus augue facilisis eu "
      "orci, nisl pellentesque ante.Nam amet sit lectus mi finibus id urna, "
      "congue velit tortor dapibus, finibus eu diam vestibulum, Ut ex. vitae "
      "iaculis vitae, ornare ut vehicula mauris, lectus Pellentesque "
      "tristique. porta nisl non eros sed Donec dapibus. enim laoreet non "
      "posuere, sapien eu dolor vulputate Nulla rutrum. porta vel nunc sodales "
      "Phasellus arcu. suscipit nec Sed sapien. vulputate eget Sed facilisi. "
      "Nulla aliquam. pulvinar mauris et lacus elementum Praesent volutpat. "
      "erat Aliquam placerat. commodo blandit Vestibulum tincidunt. facilisis "
      "id massa ultrices Praesent aliquet. varius metus amet sit sapien "
      "convallis Etiam nisl. dapibus condimentum vitae, orci eget interdum "
      "tortor, massa sagittis.Vestibulum non enim vel tempus Vivamus risus. eu "
      "auctor rutrum gravida nulla amet sit dui eu Sed auctor. imperdiet vel "
      "odio aliquet Duis ante. amet sit pulvinar non, imperdiet id accumsan "
      "elit, nulla Aenean tortor. feugiat convallis id, diam sed lacinia dui, "
      "magna Suspendisse tincidunt. elementum leo viverra id nisi, interdum "
      "rutrum Cras feugiat. fermentum leo imperdiet quis ante, iaculis cursus "
      "Mauris tincidunt. porta et libero tristique Cras pretium. risus commodo "
      "ac molestie, diam vitae turpis fermentum Quisque feugiat. vulputate "
      "erat aliquet eget tortor, metus interdum In urna. ut porttitor bibendum "
      "feugiat eros tempor arcu quis Pellentesque tempor. mollis sapien at "
      "enim faucibus Integer est. efficitur nec lacus, malesuada a porta.Cras "
      "pretium non nibh blandit Morbi nibh. nisi in Integer tincidunt. "
      "hendrerit quis quam volutpat Vestibulum congue. convallis facilisis "
      "Praesent sagittis. lobortis tortor ut sapien sollicitudin Aliquam est. "
      "in et tristique molestie metus sed sem eget Etiam velit. euismod "
      "interdum lobortis, nunc id sodales ex, eros Morbi euismod. iaculis "
      "euismod Donec nec. molestie sapien facilisis vel nibh, lacus ultrices "
      "Nam tincidunt. eu mi nec venenatis eleifend.Nullam ipsum vehicula "
      "ornare mattis, mauris laoreet est placerat Nunc faucibus. auctor ex "
      "porttitor lorem scelerisque Curabitur molestie. vel risus posuere "
      "hendrerit Curabitur non. dictum neque sodales in ex, est dignissim Cras "
      "gravida. diam congue a sagittis, leo in dolor vulputate Aliquam varius. "
      "aliquet eget odio rhoncus Ut egestas. turpis ac fames malesuada et "
      "netus et senectus tristique morbi habitant Pellentesque aliquet. "
      "blandit nisl at dapibus Suspendisse potenti. Suspendisse ut. ultrices "
      "arcu suscipit sed felis, sollicitudin imperdiet Aenean metus. malesuada "
      "et venenatis.Nullam interdum quis ex auctor Nulla cursus. pellentesque "
      "eros porttitor eu purus, magna convallis Etiam justo. rutrum sed Proin "
      "congue. tincidunt nec velit blandit Maecenas dignissim. tempor "
      "porttitor Nullam enim. nunc pulvinar Vestibulum potenti. Suspendisse "
      "nisi. tempus accumsan a, purus rhoncus porttitor augue, neque Nunc "
      "amet. sit faucibus quam commodo id est, pulvinar cursus mi.Sed aliquet "
      "sodales ut, nibh sed imperdiet dolor, lacus Donec et. pellentesque dui "
      "elementum eu risus, ligula convallis Integer sed. vestibulum nulla "
      "auctor eget massa, mi tincidunt Fusce neque. arcu nec Aenean "
      "vestibulum. sem feugiat mollis aliquam, tellus maximus lectus aliquam "
      "Praesent erat. dictum a Vestibulum venenatis. egestas sem eget tellus "
      "quis ex.Nam feugiat at Pellentesque sapien. vitae sollicitudin id, "
      "mattis vitae fringilla metus, mauris Duis odio. aliquet ut, diam "
      "consectetur euismod, sapien eget Donec turpis. nunc ac Cras orci. eget "
      "non viverra consectetur lorem eget lorem nec Vestibulum auctor. ut nibh "
      "pulvinar vestibulum Curabitur erat. pretium id lacus.Nam ullamcorper eu "
      "Duis malesuada. consequat at odio blandit In ipsum. pellentesque ac "
      "Aliquam ipsum. congue faucibus mattis, purus eu ultricies diam, leo "
      "Proin tellus. efficitur id Nunc arcu. semper quis Suspendisse commodo. "
      "tincidunt diam sed risus non Curabitur felis. fringilla lacinia quis, "
      "nulla in volutpat tortor, lacus semper.Vestibulum ut magna nec lacinia "
      "Etiam vulputate. eget felis feugiat eleifend Mauris quis. rutrum ligula "
      "auctor ut mauris, odio ultrices Praesent vestibulum. justo finibus "
      "sodales hendrerit, mi vitae quam facilisis Donec ipsum. nec magna "
      "mauris suscipit ac ligula, pulvinar erat enim consectetur, tristique "
      "vel tortor facilisis, Nam orci. porttitor posuere Aliquam facilisis. "
      "vestibulum eu arcu maximus Donec egestas. accumsan sed mauris consequat "
      "Phasellus quam. ullamcorper ornare, quam dapibus ultrices, quam id Duis "
      "neque. ut interdum ut, pellentesque sed placerat quam, elit Donec ac. "
      "facilisis justo congue quis turpis, tellus fermentum Duis orci. posuere "
      "ullamcorper nec, erat vitae sagittis purus, massa Quisque luctus. a "
      "justo commodo scelerisque Nam mauris. nec dolor urna condimentum sed "
      "diam, elementum lorem ex scelerisque, porttitor vitae nunc faucibus, "
      "Quisque enim. efficitur condimentum Cras libero. nec sed interdum "
      "consectetur ipsum et tortor a tortor.Nam aliquam sagittis a, erat vel "
      "tincidunt nunc, velit Aenean ante. sodales eleifend ac, erat hendrerit "
      "pharetra lectus, neque Maecenas viverra. posuere odio consectetur "
      "egestas In ipsum. tincidunt ultrices id, odio sed mattis metus, enim "
      "Proin eu. laoreet neque ullamcorper maximus dui, erat tristique Nunc "
      "convallis. accumsan feugiat Phasellus quis. rhoncus arcu tincidunt id "
      "turpis, nibh accumsan sem.Nam vulputate metus lacus lacinia non dui, "
      "porttitor nibh diam dignissim, lacinia amet sit erat congue, Maecenas "
      "finibus. maximus sed ante vestibulum Donec purus. imperdiet non urna, "
      "tempus a Aenean sed. pellentesque turpis condimentum nec nisl, magna "
      "pretium Vivamus mi. eleifend amet sit Ut faucibus. ac elit luctus "
      "viverra Pellentesque tempor. nisl eleifend at varius, tellus at turpis "
      "fermentum Aliquam nec. vehicula eros rhoncus eget tellus, aliquet "
      "porttitor Curabitur ac. lacinia diam consectetur non nunc, dolor "
      "hendrerit Duis justo. feugiat sed Vestibulum sollicitudin. eget risus "
      "mollis egestas Etiam scelerisque. dapibus et magna lobortis Nullam "
      "elit. id congue vitae, egestas nec viverra lectus, ligula Aliquam enim. "
      "non eros velit posuere bibendum urna, condimentum ligula risus "
      "elementum, accumsan et ligula tristique, ipsum.Aliquam laoreet in Cras "
      "varius. varius semper Vestibulum justo. condimentum eget turpis, "
      "dignissim nec Morbi mauris. et tristique tincidunt cursus ex vel leo "
      "amet sit Nunc enim. ac risus arcu tempor vel justo, volutpat dui quam "
      "condimentum, dictum ac ipsum volutpat, Vestibulum est. eu id posuere "
      "luctus mauris non justo quis Curabitur arcu. pretium a, enim efficitur "
      "tempus, nunc amet sit Integer nulla. amet sit aliquet quis, dignissim "
      "quis accumsan eros, neque Nullam cursus. fermentum a ligula ornare "
      "Aliquam varius. egestas malesuada Donec velit. iaculis eu fringilla "
      "maximus augue ut est eget Donec lorem. dolor eget Donec lobortis. "
      "tincidunt porta Nullam tellus. finibus at Cras orci. eleifend at "
      "nunc.Sed aliquam non, sapien consectetur gravida, mauris id Donec nisi. "
      "tempus vel, neque pharetra condimentum, lorem non Fusce eleifend. "
      "accumsan ligula vestibulum nisl amet sit Donec lorem. lacinia sed "
      "ipsum, luctus a Fusce arcu. sed non gravida mattis turpis nec augue sed "
      "Aenean leo. tempor ut arcu, ultrices id Curabitur dui. vitae in "
      "consequat porta tellus at nibh varius Suspendisse scelerisque. "
      "efficitur eget turpis commodo Nunc diam. placerat in nibh, dictum ut "
      "Pellentesque pharetra. pretium id diam placerat ac.Mauris accumsan orci "
      "convallis a mi, velit commodo Nullam odio. ex a Nullam eleifend. "
      "molestie eu velit egestas Pellentesque lorem. aliquet in, justo "
      "fermentum dictum, metus nec Aliquam maximus. egestas arcu in elit "
      "pharetra Suspendisse et. bibendum ex vulputate ut massa, sodales "
      "pulvinar Praesent fringilla. interdum sem non eros posuere Ut gravida. "
      "congue vel elit imperdiet blandit.Fusce tincidunt ut mauris aliquet "
      "Integer porttitor. vitae ex fermentum aliquam Fusce posuere. "
      "condimentum efficitur Phasellus odio. ut scelerisque vel, pulvinar eget "
      "pellentesque velit, magna Donec libero. dignissim vitae Maecenas elit. "
      "finibus ac, urna vestibulum dignissim, odio in Pellentesque neque. "
      "maximus lobortis ac, enim eu pellentesque nunc, nulla Fusce facilisi. "
      "Nulla facilisis. ullamcorper tristique Aliquam tellus. vestibulum vel, "
      "enim cursus consectetur, ex ut Ut nisl. interdum non, ipsum efficitur "
      "finibus, felis et Nulla vitae. finibus nibh ornare nec felis, ex "
      "vestibulum Nam non. suscipit sem eleifend in diam, sem luctus "
      "commodo.Praesent nec ipsum at tempor Fusce sem. vitae leo ligula dictum "
      "ac leo, posuere dui eros egestas, vehicula et nibh scelerisque, Proin "
      "ullamcorper. vehicula mi a orci vitae Nam ex. tincidunt eget, dolor "
      "semper consectetur, diam eget Mauris suscipit. amet sit felis egestas "
      "dictum Vestibulum sapien. dignissim volutpat vitae, urna in ultrices "
      "sapien, lacus Mauris condimentum. porttitor metus amet sit nisl sed "
      "Nulla congue. non odio bibendum elementum Praesent non. pellentesque "
      "metus commodo eu massa, laoreet pretium Aliquam purus. blandit eget "
      "Donec nisi. augue ac ligula.Nam quis auctor eu, feugiat et malesuada "
      "enim, mi In faucibus. in primis ipsum ante ac fames malesuada et "
      "Interdum id. pharetra neque pulvinar ut quam, sem facilisis In "
      "dignissim. volutpat eget est auctor Sed tellus. imperdiet a, turpis "
      "aliquam tempus, leo aliquet Donec nibh. commodo feugiat ante, placerat "
      "a Vestibulum viverra. elit efficitur eget mollis, justo elementum "
      "ligula tristique Praesent mus. ridiculus nascetur montes, parturient "
      "dis magnis et penatibus natoque varius dignissim.Orci felis faucibus "
      "nec sagittis, purus vitae erat tincidunt Maecenas iaculis. malesuada "
      "felis eu erat mollis Nullam nisl. rhoncus vel Fusce semper. viverra "
      "metus sed neque bibendum Phasellus id. auctor felis efficitur a sem, "
      "eros porta Proin malesuada. venenatis tempor Nulla velit. nunc amet sit "
      "Cras fringilla. volutpat enim tincidunt non dui, odio suscipit Sed "
      "massa. suscipit convallis at, enim quis ullamcorper orci, lacus Mauris "
      "euismod. pretium ornare Mauris scelerisque. feugiat pharetra Nullam "
      "sagittis. vel diam a gravida Donec blandit. rhoncus nulla scelerisque "
      "eget nisl, facilisis ornare augue.Aliquam erat ut Cras vehicula. rutrum "
      "tellus at augue eget Nam ipsum. egestas ut, nisi porttitor interdum, "
      "erat fringilla Pellentesque lectus. eget varius vel, tincidunt amet sit "
      "malesuada risus, odio Sed faucibus. pharetra auctor Vestibulum mauris. "
      "non eget viverra vulputate turpis cursus quam in Fusce pulvinar. amet "
      "sit sapien amet sit tempus Ut augue. condimentum ornare in, magna et "
      "luctus dolor, nulla Sed turpis. ex amet sit Etiam nisl. eros at "
      "lacinia.Phasellus convallis felis maximus lorem pellentesque Aliquam "
      "semper. id libero consectetur vulputate Fusce faucibus. in primis ipsum "
      "ante ac fames malesuada et Interdum facilisi. Nulla tortor. quis lorem "
      "orci placerat ac libero, viverra massa urna feugiat, pharetra eu purus "
      "ultrices, Donec dignissim. euismod quam finibus orci varius Donec dui. "
      "faucibus id, nunc pellentesque imperdiet, augue quis Suspendisse "
      "aliquam. faucibus sed diam mattis Sed leo. semper id Nam dolor. "
      "pharetra at, nisl aliquet tempor, lorem ac Pellentesque commodo. mi "
      "tincidunt consequat fringilla, leo amet sit tortor gravida Morbi ac. "
      "vulputate nisi sagittis non ligula, porta consequat Vestibulum nisi. "
      "sed feugiat eu, auctor vestibulum luctus leo, odio Mauris sed. "
      "condimentum magna rutrum a est, justo viverra Vivamus molestie. "
      "pharetra nunc vel dolor iaculis Integer massa. varius ac velit, varius "
      "at Ut elit. adipiscing consectetur amet, sit dolor ipsum Lorem";
  reverse_words(text);
  EXPECT_EQ(expected, text);
}
